---
sudo: false
dist: trusty
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=isort
install:
  - pip install tox
  - pip install coveralls
script:
  - pytest tests.py
  - flake8 .
  - isort --check-only
after_success:
  - coveralls
